name: waste-detector
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip
  - conda
  - openssl
  - python=3.10.6
  - cudatoolkit=11.3
  - pytorch=1.12.0+cu11.3
  - pycocotools=2.0.4
  - pillow=9.2.0
  - pandas
  - numpy
  - opencv
  - matplotlib
  - libpng
  - jpeg
  - ipykernel
  - ipywidgets
  - ipython
  - codecarbon=2.1.4
  - cython
  - ffmpeg
  - notebook
  - nb_conda_kernels
  - jupyter_contrib_nbextensions
  - nbconvert
  - pyyaml
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - torchmetrics
  - tqdm
  - wheel
