name: waste-detector
channels:
  - defaults
dependencies:
  - python==3.10
  - conda
  - pillow==9.2.0
  - numpy
  - pandas
  - opencv
  - matplotlib
  - libpng
  - jpeg
  - ffmpeg
  - ipykernel
  - ipython
  - notebook
  - nb_conda_kernels
  - yaml
  - scikit-learn
  - scipy
  - seaborn
  - pip
  - ipywidgets
  - widgetsnbextension
  - tqdm